allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp3
parameters:
  type: gp3
# provisioner: ebs.csi.aws.com
provisioner: ebs.csi.eks.amazonaws.com # This is important for EKS Auto Mode
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
